### ISSUE TITLE
Content shifts to right on tablets

### ISSUE THREAD

**Issue by JM480** [benarmstead/OfflineCookBook#5]
The content in the app shifts to the right on tablets in Landscape Mode leaving unused space on the left. I've only noticed this issue on my tablet, this doesn't happen on my phone.

**Comment by benarmstead** [comment]
Thanks for reporting I'll work on it

**Comment by benarmstead** [comment]
Will be fixed in https://github.com/benarmstead/OfflineCookBook/issues/7
