### ISSUE TITLE
Certain Recipe Links Crash The App

### ISSUE THREAD

**Issue by JM480** [benarmstead/OfflineCookBook#6]
Recipe links that lead to other recipes within the app cause it to crash such as the link to pasta sauce from the chicken parmesan recipe.

**Comment by benarmstead** [comment]
Thank you for your bug report contributions. I won't  be attempting to fix them within the current app version as I have bigger plans for the project which will include a re write (in which the reported bugs won't be present). More information can be found here https://github.com/benarmstead/OfflineCookBook/issues/7

If you know any react native then I would certainty be open to contributors?

**Comment by benarmstead** [comment]
Will be fixed in https://github.com/benarmstead/OfflineCookBook/issues/7

**Comment by JM480** [comment]
> Thank you for your bug report contributions. I won't be attempting to fix them within the current app version as I have bigger plans for the project which will include a re write (in which the reported bugs won't be present). More information can be found here #7
> 
> If you know any react native then I would certainty be open to contributors?

I don't know how to code so I won't be able to help with development of the app.
