### ISSUE TITLE
Create better cross platform solution

### ISSUE THREAD

**Issue by benarmstead** [benarmstead/OfflineCookBook#7]
The current android client is a start, however my ambition is to create a cross platform solution to viewing the recipes. This may take some time as I am currently very busy, however it is my long term goal for the project.

Requirements:
- Web support
- Android offline client
- Search  feature

I am considering the following possible solutions:
- Build whole app in react native, allowing for a web version, as well as an offline android and ios version with a search feature
- Use a hugo theme with a search feature for the web version and then serve this web version offline in an android app
- Use a hugo theme with a search feature for the web version and then distribute as an app via a PWA

Personally I think the first solution is the best and most suitable, however it is also the most time consuming, and as I have limited time to work on this project, it may be a while before it could be fully implemented.

Feel free to add suggestions below.

**Comment by JM480** [comment]
Do you think you'll be able to support Linux and Linux mobile for devices like the Pinephone Pro?

**Comment by benarmstead** [comment]
Obviously Linux & Pinephones would be able to view the web version, however as far as a native client, to start with, no.

Once the client described above is complete, then this would be the next task to complete. Most likely done by serving the web version offline in some sort of wrapper. I use Linux myself so this is definitely something I would want in the future. The reason for the initial focus on mobile is usually when I am cooking I find myself using more portable devices rather than Laptops/PC's, but I see the value in it for Pinephone support as well as having an offline copy of recipes on desktop.

**Comment by benarmstead** [comment]
I have decided on using flutter as the framework for the new Offline Cook Book, flutter offers android, ios, linux, mac, windows support, therefore should make development a lot easier. I don't know any flutter yet though :)
