### ISSUE TITLE
Link to F-Droid on ReadMe is broken

### ISSUE THREAD

**Issue by VishnuSanal** [benarmstead/OfflineCookBook#8]
The hyperlink should point to https://www.f-droid.org/packages/com.benarmstead.simplecooking/

It currently points to https://benarmstead.github.io/fdroid/repo?fingerprint=9CCBC7C297F0B54520834681D1D29C2184B2CD262E80AA9E453215284ED3D684 which gives a 404

**Comment by benarmstead** [comment]
Fixed now, thanks a lot for spotting!
