### ISSUE TITLE
Localization into Italian

### ISSUE THREAD

**Issue by r4box** [benarmstead/OfflineCookBook#9]
Hello, I would like to attempt a localization of your app into Italian for a university project. Where can I find the localizable strings? Thank you in advance!

**Comment by benarmstead** [comment]
Hi, that sounds great! Unfortunately this app doesn't handle strings like most others. The app itself is actually just a website that is stored locally and displayed (which isn't a great way to do it so I am currently re-writing it but it's been slow progress as I have been busy).

The string's which are used in the app though are at [/master/recipes/markdown](https://github.com/benarmstead/OfflineCookBook/tree/master/recipes/markdown) and when I get round to finishing the re-write these same strings will be used, so maybe for e.g. apple pie, then a file such as recipes/markdown/italian/apple-pie.md.

I'm not sure how this fits in with your project or not, so if you have any further questions feel free to email 
 temporary@benarmstead.co.uk
